### ISSUE TITLE
prerequisites

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra.github.io#104]
Hi,

I try to build the Jekyll project locally, but i think we can't build with the last jekyll / ruby version.
In fact we get some dependancies version errors during the jekyll build.

So, what are the prerequisites (dependancies, version, others...)  to build and change this project ? 

I see jekyll with ruby 2.3.3 here : 
https://github.com/georchestra/georchestra.github.io/blob/0f2ca29440179d9ae90fcb3422b1519c21d4d9fa/.travis.yml#L12-L13

**Comment by fvanderbiest** [comment]
Indeed no version was specified at that time ...
Two paths IMO:
- either use an older version (6 years ago !) to build locally - I would not encourage it
- or upgrade to a newer version, though I dunno what this involves really

**Comment by Gaetanbrl** [comment]
> either use an older version (6 years ago !) to build locally - I would not encourage it

I confirm that with Debian 11 + rvm, we can't install ruby 2.3.x (or maybe with manual install from tar.gz).

Well,  an upgrade could be a better solution (IMO)...

**Comment by pierrejego** [comment]
close with #105  
ruby version not used anymore
