### ISSUE TITLE
Replace travis by github actions

### ISSUE THREAD

**Issue by pierrejego** [georchestra/georchestra.github.io#105]
![image](https://user-images.githubusercontent.com/11499415/144589153-12d07da3-5cd1-4068-b39c-248f75b563f1.png)

 Dependency Error: Yikes! It looks like you don't have kramdown-parser-gfm or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown-parser-gfm' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2010-06-09-georchestra-aux-RMLL-Bordeaux.md':
                    kramdown-parser-gfm
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    kramdown-parser-gfm
The command "jekyll build --safe && htmlproofer --allow_hash_href --only_4xx --file_ignore /blog/201[0-5]/ ./_site" exited with 1.

We propose to update version and correct travis build. To add kramdown-parser-gfm

**Comment by pierrejego** [comment]
Since Travis.org is end of term, I propose to build and test via github actions

**Comment by fvanderbiest** [comment]
Yep, sounds like a neat idea !

**Comment by pierrejego** [comment]
GIt action created, but there is a link to be corrected in website to have a build succeed

Checking 148 external links...
- /github/workspace/_site/community.html
Ran on 32 files!
  *  External link https://sigweb.cmnordeste.pt/ failed: 404 No error

**Comment by fvanderbiest** [comment]
> * External link https://sigweb.cmnordeste.pt/ failed: 404 No error

:-(
It should probably be removed then

**Comment by pierrejego** [comment]
Modification done with this commit https://github.com/georchestra/georchestra.github.io/pull/110/commits/ce62ca6ba261320bd8091081283a0daa1558836a
