### ISSUE TITLE
GeOrchestra users list in the cards

### ISSUE THREAD

**Issue by Agath21** [georchestra/georchestra.github.io#116]
![Georchestra_community_catalogue](https://user-images.githubusercontent.com/22764056/146029065-fb125fdb-8c85-4368-b689-87182ab291d8.png)

I propose to transform the list of GeOrchestra users into a catalog. As on the model, a user = a card with a name, a image and a link to the application.

What do you think about it?

**Comment by fvanderbiest** [comment]
100 % agree on it Agathe !

**Comment by pierrejego** [comment]
@Agath21  can you use image with smaller size ? for example public/community-users/oeiras30mais.png is 21.Mo
