### ISSUE TITLE
broken urls

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra.github.io#71]
- ./_site/blog/2010/10/01/openstreetmap-et-ids/index.html
  *  External link http://geobretagne.fr/mapfishapp failed: got a time out (response code 301)
  *  External link http://maps.qualitystreetmap.org/?zoom=12&lat=6066711.44625&lon=-373896.02136&layers=B00F00 failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
- ./_site/blog/2011/02/14/les-wps-reve-ou-realite/index.html
  *  External link http://www.geoconnections.org/fr/communities/developers/standards/web_processing_service failed: got a time out (response code 0)
- ./_site/blog/2011/09/01/services-non-ouverts/index.html
  *  External link http://api.maps.ovi.com failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
  *  External link http://trac.osgeo.org/openlayers/ticket/3481 failed: 404 No error
- ./_site/blog/2011/10/21/openlayers-client-zoom-une-solution-pour-les-services-tuiles/index.html
  *  External link http://elemoine.github.com/openlayers/examples/clientzoom.html failed: 404 No error
1m  *  External link http://www.camptocamp.com/en/blog/2011/10/openlayers-client-zoom-feature/trackback failed: 404 No error
- ./_site/blog/2011/12/17/pigma-nouvelle-plateforme-georchestra/index.html
  *  External link http://ids.pigma.org/mapfishapp failed: 301 SSL peer certificate or SSH remote key was not OK
- ./_site/blog/2011/12/23/geoserver-2.1.3-est-dans-les-bacs/index.html
  *  External link http://geobretagne.fr/context/default-geobretagne.wmc failed: got a time out (response code 301)
- ./_site/blog/2011/12/23/openlayers-nouveaux-effets-zoomapparition/index.html
  *  External link http://maps.google.fr failed: got a time out (response code 0)
- ./_site/blog/2012/06/12/zoom-sur-l-explorateur-de-catalogue/index.html
  *  External link http://blog.georchestra.org/public/mapfishapp-cswbrowser.png failed: got a time out (response code 301)
- ./_site/blog/2013/05/31/community-meeting-georchestra-merci-a-tous/index.html
  *  External link https://www.pigma.org/reunions-nationales failed: 404 No error
- ./_site/blog/2013/10/02/georchestra-13.09/index.html
  *  External link http://sdi.georchestra.org/mapfishapp/?lang=es failed: 502 No error
- ./_site/blog/2014/02/03/release-14.01/index.html
  *  External link http://geobretagne.fr/mapfishapp/?lang=en failed: got a time out (response code 301)
  *  External link http://sdi.georchestra.org/mapfishapp/map/0c3641dfaade3b5c366f78eac125fd7e?lang=en failed: 502 No error
  *  External link http://sdi.georchestra.org/mapfishapp/map/0d05bc8b10db4c292639db9e6d713641?lang=en failed: 502 No error
- ./_site/blog/2014/02/03/version-14.01/index.html
  *  External link http://geobretagne.fr/mapfishapp failed: got a time out (response code 301)
  *  External link http://sdi.georchestra.org failed: 502 No error
  *  External link http://sdi.georchestra.org/sviewer/?layers=geor:sdi failed: 502 No error
  *  External link http://sdi.georchestra.org/sviewer/?wmc=468401c3b96667adfe2af8d261b82b01 failed: 502 No error
- ./_site/blog/2014/04/13/geocom-2014-in-france/index.html
  *  External link http://framadate.org/ge61u7wm8hz3yk7w failed: got a time out (response code 301)
- ./_site/blog/2014/04/13/geocom-2014/index.html
  *  External link http://framadate.org/7s9f54w6ajppjjs9 failed: got a time out (response code 301)
- ./_site/blog/2014/07/09/upgrade-to-geoserver-2.5.1/index.html
  *  External link http://cms.geobretagne.fr failed: got a time out (response code 302)
  *  External link http://sdi.georchestra.org/geoserver/web failed: 502 No error
- ./_site/blog/2015/01/30/georchestra-14.12-is-available/index.html
  *  External link http://craig.fr failed: got a time out (response code 301)
  *  External link http://sdi.georchestra.org/maven/repository failed: 502 No error
- ./_site/blog/2015/02/06/geocom2015-announced/index.html
  *  External link http://www.cigalsace.org failed: got a time out (response code 0)
- ./_site/blog/2015/04/06/codesprint-a-beg-meil/index.html
  *  External link http://geobretagne.fr/m/?x=-443596&y=6083708&z=18&lb=1&title=codesprint+geOrchestra failed: got a time out (response code 301)
- ./_site/blog/2015/06/16/codesprint-report/index.html
  *  External link http://sdi.georchestra.org/mapfishapp failed: 502 No error
- ./_site/blog/2016/03/05/georchestra-15.12-fr/index.html
  *  External link http://build.georchestra.org failed: got a time out (response code 301)
  *  External link https://build.georchestra.org/ci/job/georchestra-generic-wars failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL peer certificate or SSH remote key was not OK
- ./_site/blog/2016/05/16/geocom-2016-fr/index.html
  *  External link http://www.pigma.org/rencontres-georchestra-geocom2016 failed: 404 No error
- ./_site/community.html
  *  External link http://sdi.georchestra.org/mapfishapp/map/115616d003157b65fb55701c5b240747 failed: 502 No error
  *  External link http://www.cigalsace.org/portail failed: got a time out (response code 0)
- ./_site/index.html
  *  External link http://sdi.georchestra.org/mapfishapp/?wmc=app/contexts/relief.wmc failed: 502 No error
- ./_site/project.html
  *  External link http://geobretagne.fr failed: got a time out (response code 301)
- ./_site/software.html
[31m  *  External link https://github.com/georchestra/geonetwork/blob/georchestra-gn3-3.0.x/README.md failed: 404 No error
htmlproofer 3.6.0 | Error:  HTML-Proofer found 37 failures!

**Comment by severo** [comment]
Some others in main pages (not the blog):

In https://www.georchestra.org/{.,es,fr}/software.html:

 - https://github.com/georchestra/geonetwork/blob/georchestra-gn3-3.0.x/README.md
 - https://github.com/georchestra/georchestra/blob/master/ldapadmin/README.md

In https://www.georchestra.org/{.,es}/community.html

-  http://terranis.fr/en/

**Comment by severo** [comment]
See also https://github.com/GeoWebCache/geowebcache/issues/716, related to a broken link in https://www.georchestra.org/es/documentacion.html, https://www.georchestra.org/documentation.html and https://www.georchestra.org/fr/documentation.html

**Comment by severo** [comment]
Note that while we do not fix this issue, or remove the "LinkCheck" option in TravisCI, the CI will fail.

See https://travis-ci.org/georchestra/georchestra.github.io/builds/455736090?utm_source=github_status&utm_medium=notification

**Comment by fvanderbiest** [comment]
yep ...

**Comment by pierrejego** [comment]
Update gitaction to ignore all urls from old blog (previous 2017)
