### ISSUE TITLE
Releases table is outdated

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra.github.io#78]
https://www.georchestra.org/software.html

**Comment by fvanderbiest** [comment]
Missing 18.06 indead !

**Comment by fvanderbiest** [comment]
https://packages.georchestra.org/ also does not mention 18.06

**Comment by fvanderbiest** [comment]
Maybe we should just redirect the user to https://github.com/georchestra/georchestra/releases ?

**Comment by fvanderbiest** [comment]
This table is a burden to maintain, and does not really help...
